// auto-generated by tools/build_report_html.py — do not edit
window.PORTAL_KA_STATS = {
  "file": "08_제출내역서/청원지구_단가통합(전기제외)_ka.xlsx",
  "sumDesc": "★ 제출 최종 · 직접 6,446,083,485원 · 도급 11,414,018,367원 · 미확정 검토 0 / 미매칭 20",
  "directWon": 6446083485,
  "directOku": "64.46",
  "contractWon": 11414018367,
  "contractOku": "114.14",
  "contract4Oku": "113.70",
  "contractMult": 1.771,
  "review": 0,
  "unmatched": 20,
  "gayeonghyeon": 255,
  "pendingTotal": 20,
  "matOku": "15.23",
  "labOku": "41.29",
  "expOku": "7.94"
};
