// auto-generated by tools/build_consolidated_summary.py — do not edit
window.PORTAL_STATS = {
  "sumDesc": "직접공사비 7,136,910,628원 · 매칭 932 / 검토 157 / 미매칭 125 (76.8%)",
  "directWon": 7136910628,
  "directOku": "71.37",
  "matched": 932,
  "review": 157,
  "unmatched": 125,
  "total": 1214,
  "matchRate": "76.8",
  "contractOku": "118.95",
  "contractMult": 1.667,
  "contractWon": 11894693068,
  "matOku": "20.20",
  "labOku": "43.13",
  "expOku": "8.04"
};
